spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- PayPal sandbox credentials ---
paypal.client.id=AZVCr6-aiO8IR7u2f3Ug_5gECXBlrClQmp_yegk96-57j-qykBGhx0oPTYUnCdeCwYAZhTN7zk5L4zeF
paypal.client.secret=EEXBhhfUD7-gK5y-duh8Fk57XWcNWJJLpfni9egnVA-lh4gQWxJpeN9oDdYeaU0hzqdEaQ41hEXgCi9P
paypal.mode=sandbox


jwt.secret=Y3VzdG9tRWNvbW1lcmNlU2VjcmV0S2V5Rm9ySldUU2lnbmluZ011c3RCZTMyQnl0ZXNPckxvbmdlcg==